<?php if(!defined('HDPHP_PATH'))EXIT;
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('1','webname','HDPHP社区--中国最强PHP培训机构  《后盾网》','站点配置','网站名称','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('2','icp','京ICP备12048441号-3','站点配置','ICP备案号','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('3','html_path','html','站点配置','静态html目录','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('4','copyright','Copyright © 2012-2013 HDCMS 后盾网 版权所有','站点配置','网站版权信息','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('5','keywords','php培训,php实训,后盾网','站点配置','网站关键词','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('6','description','后盾网顶尖PHP培训 内容全面 全程实战!业内顶级讲师亲自授课,千余课时独家视频教程免费下载,超百G原创视频资源,实力不容造假!010-64825057','站点配置','网站描述','多行文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('152','email','houdunwangxj@gmail.com','站点配置','管理员邮箱','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('9','backup_dir','backup','高级设置','数据备份目录','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('10','web_open','1','站点配置','网站开启','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('15','auth_key','houdunwang.com','安全设置','cookie加密KEY','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('16','upload_path','upload','上传配置','上传目录','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('17','upload_img_path','img','上传配置','上传图片目录','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('18','allow_type','jpg,jpeg,png,bmp,gif','上传配置','允许上传文件类型','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('19','allow_size','2048000','上传配置','允许上传大小（字节）','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('20','water_on','0','水印设置','上传文件加水印','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('115','member_verify','0','会员设置','会员注册是否需要审核','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('116','reg_show_code','1','会员设置','会员注册是否显示验证码','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('119','reg_email','1','会员设置','注册成功是否发邮件','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('120','reg_interval','0','会员设置','2次注册间隔间间','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('121','default_member_group','4','会员设置','新注册会员初始组','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('123','token_on','0','安全设置','表单使用令牌验证','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('124','log_key','houdunwang.com','安全设置','日志文件加密KEY','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('125','session_name','hdsid','安全设置','SESSION_NAME值','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('126','super_admin_key','SUPER_ADMIN','安全设置','站长令牌名称','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('127','tel','010-64825057','站点配置','联系电话','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('128','water_text','houdunwang.com','水印设置','水印文字','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('129','water_text_size','16','水印设置','文字大小','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('130','water_img','data/water/water.png','水印设置','水印图像','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('131','water_pct','0','水印设置','水印图片透明度','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('132','water_quality','90','水印设置','图片压缩比','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('133','water_pos','9','水印设置','水印位置','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('134','del_content_model','0','高级设置','删除文章先放入回收站','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('136','down_remove_pic_size','500','高级设置','下载远程资源允许最大值','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('168','reply_credits','1','会员设置','回复奖励积分','文本','会员提交回复奖励积分')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('142','down_remote_pic','0','内容相关','下载远程图片','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('143','auto_desc','1','内容相关','截取内容为摘要','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('144','auto_thumb','0','内容相关','提取内容图片为缩略图','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('145','upload_img_max_width','600','内容相关','上传图片宽度超过此值，进行缩放','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('146','upload_img_max_height','600','内容相关','上传图片高度超过此值，进行缩放','数字','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('149','member_open','1','会员设置','开启会员中心','布尔(1/0)','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('150','web_close_message','网站维护中，请稍候访问','站点配置','网站关闭提示信息','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('151','web_style','default','私有配置','网站模板','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('155','qq','1455067020','站点配置','QQ号','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('154','weibo','houdunwangxj@gmail.com','站点配置','新浪微博','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('156','tweibo','houdunwang@gmail.com','站点配置','腾讯微博','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('157','email','houdunwangxj@gmail.com','站点配置','企业邮箱','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('158','init_credits','100','会员设置','初始积分','文本','')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('161','cache_index','-1','性能优化','首页缓存时间','文本','（单位：秒，-1不缓存 0永久缓存)')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('162','cache_category','-1','性能优化','栏目缓存时间','文本','（单位：秒，-1不缓存 0永久缓存)')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('163','cache_content','-1','性能优化','文章缓存时间','文本','（单位：秒，-1不缓存 0永久缓存)')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('164','comment_step_time','10','会员设置','评论间隔时间','文本','必须大于1（单位秒)')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('166','pathinfo_type','0','伪静态','开启伪静态','布尔(1/0)','需要环境支持')");
$db->exe("REPLACE INTO ".$db_prefix."config (`id`,`name`,`value`,`type`,`title`,`show_type`,`message`) VALUES('167','open_rewrite','0','伪静态','开启Rewrite','布尔(1/0)','1 服务器需要支持Rewrtie 2 将HDCMS根目录中的htaccess.txt改名为.htaccess')");
